apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: lh-kafka
  namespace: kafka
spec:
  kafka:
    version: 3.2.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.2"
      auto.topics.create.enable: "false"
      replica.lag.time.max.ms: 20000
    rack:
      topologyKey: topology.kubernetes.io/zone
    storage:
      type: jbod
      class: lh-resizable-gp2
      volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        deleteClaim: true
  # ZooKeeper is required when validating the CR spec. However it's ignored by the
  # controller when UseKRaft is set.
  zookeeper: 
    replicas: 1
    storage:
      type: persistent-claim
      size: 5Gi
      deleteClaim: true
  # entityOperator:
  #   topicOperator: {}
  #   userOperator: {}
---
