# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: trailing-whitespace
            exclude: (server|client)/src/main/java/io/littlehorse(/sdk)?/common/proto/.*
          - id: end-of-file-fixer
            exclude: (server|client)/src/main/java/io/littlehorse(/sdk)?/common/proto/.*
          - id: check-yaml
          - id: check-added-large-files
    - repo: https://github.com/shellcheck-py/shellcheck-py
      rev: v0.9.0.2
      hooks:
        - id: shellcheck
          args: [-x]
    - repo: https://github.com/hadolint/hadolint
      rev: v2.12.1-beta
      hooks:
        - id: hadolint-docker
    - repo: local
      hooks:
          - id: prettier
            name: Prettier
            language: system
            always_run: true
            pass_filenames: false
            entry: npm run format
          - id: compile-proto
            name: Compile proto files
            language: system
            always_run: true
            pass_filenames: false
            entry: ./local-dev/compile-proto.sh
          - id: tests
            name: Running Tests
            language: system
            always_run: true
            pass_filenames: false
            entry: ./gradlew test
