---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lh-server
  namespace: default
  labels:
    app: lh-server
    io.littlehorse/active: "true"
spec:
  replicas: 6
  serviceName: lh-server
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: lh-server
  template:
    metadata:
      labels:
        app: lh-server
        littlehorse.io/active: "true"
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: lh-server
      serviceAccountName: lh-server
      containers:
      - name: lh-server
        image: littlehorse:latest
        imagePullPolicy: IfNotPresent

        startupProbe:
          exec:
            command:
            - /lhctl
            - k8sHealth
          failureThreshold: 5
          periodSeconds: 3

        livenessProbe:
          exec:
            command:
            - /lhctl
            - k8sHealth
          failureThreshold: 2
          periodSeconds: 3

        readinessProbe:
          exec:
            command:
              - /lhctl
              - k8sHealth
              - --readiness
          failureThreshold: 1
          periodSeconds: 3

        env:
        - name: LHORSE_KAFKA_BOOTSTRAP
          value: "lh-kafka-kafka-bootstrap.kafka:9092"
        - name: "LHORSE_KAFKA_GROUP_ID"
          value: "server"
        - name: "LHORSE_KAFKA_GROUP_IID"
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: "LHORSE_RACK_ID"
          # TODO: this is a hack that only works on KIND. We need to create an
          # init contianer which fetches the cloud AZ from the K8s API and then
          # stuffs it in the environment somewhere.
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName

        - name: "LHORSE_CLUSTER_PARTITIONS"
          value: "72"
        - name: "LHORSE_REPLICATION_FACTOR"
          value: "3"
        - name: "LHORSE_NUM_STREAM_THREADS"
          value: "8"
        - name: "LHORSE_COMMIT_INTERVAL"
          value: "50"
        - name: "LHORSE_KAFKA_STREAMS_STATE_DIR"
          value: "/kafkaStateStores"
        - name: "LHORSE_NUM_STANDBY_REPLICAS"
          value: "2"


        - name: "LHORSE_DEFAULT_TIMEOUT"
          value: "15"
        - name: "LHORSE_KAFKA_TOPIC_PREFIX"
          value: ""

        - name: LHORSE_ADVERTISED_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: LHORSE_API_ADVERTISED_PORT
          value: "5000"
        - name: LHORSE_API_BIND_PORT
          value: "5000"
        - name: LHORSE_INTERNAL_ADVERTISED_PORT
          value: "5001"
        - name: LHORSE_INTERNAL_BIND_PORT
          value: "5001"

        ports:
        - containerPort: 5000
        - containerPort: 5001
        command: ['/server']
        volumeMounts:
        - name: streams-state
          mountPath: /kafkaStateStores
  volumeClaimTemplates:
  - metadata:
      name: streams-state
      labels:
        littlehorse.io/kafka-state-dir: "true"
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "standard"
      resources:
        requests:
          storage: 5Gi
