---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lh-server
  namespace: default
  labels:
    app: lh-server
    io.littlehorse/active: "true"
spec:
  replicas: 6
  serviceName: lh-server
  selector:
    matchLabels:
      app: lh-server
  template:
    metadata:
      labels:
        app: lh-server
        littlehorse.io/active: "true"
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: lh-server
      serviceAccountName: lh-server
      containers:
      - name: lh-server
        image: littlehorse:latest
        imagePullPolicy: IfNotPresent

        startupProbe:
          httpGet:
            path: /live
            port: 5000
          failureThreshold: 10
          periodSeconds: 3

        livenessProbe:
          httpGet:
            path: /live
            port: 5000
          failureThreshold: 3
          periodSeconds: 3

        readinessProbe:
          httpGet:
            path: /ready
            port: 5000
          failureThreshold: 1
          periodSeconds: 10

        env:
        - name: LHORSE_KAFKA_BOOTSTRAP
          value: "lh-kafka-kafka-bootstrap.kafka:9092"
        - name: "LHORSE_KAFKA_GROUP_ID"
          value: "server"
        - name: "LHORSE_KAFKA_GROUP_IID"
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: "LHORSE_KAFKA_STREAMS_STATE_DIR"
          value: "/kafkaStateStores"
        - name: LHORSE_ADVERTISED_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: LHORSE_ADVERTISED_PORT
          value: "5000"
        - name: "LHORSE_ADVERTISED_PROTO"
          value: "http"
        - name: "LHORSE_CLUSTER_PARTITIONS"
          value: "72"
        - name: "LHORSE_TASK_PARTITIONS"
          value: "12"
        - name: "LHORSE_REPLICATION_FACTOR"
          value: "3"
        - name: "LHORSE_NUM_STREAM_THREADS"
          value: "8"
        - name: "LHORSE_NUM_STANDBY_REPLICAS"
          value: "1"
        - name: "LHORSE_COMMIT_INTERVAL"
          value: "50"
        - name: "LHORSE_API_HOST"
          value: "localhost"
        - name: "LHORSE_API_PORT"
          value: "5000"
        ports:
        - containerPort: 5000
        command: ['java', '-cp', '/littleHorse.jar', 'io.littlehorse.App', 'server']
        volumeMounts:
        - name: streams-state
          mountPath: /kafkaStateStores
  volumeClaimTemplates:
  - metadata:
      name: streams-state
      labels:
        littlehorse.io/kafka-state-dir: "true"
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "standard"
      resources:
        requests:
          storage: 1Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lh-scheduler
  namespace: default
  labels:
    app: lh-scheduler
    io.littlehorse/active: "true"
spec:
  serviceName: lh-scheduler
  replicas: 6
  selector:
    matchLabels:
      app: lh-scheduler
  template:
    metadata:
      labels:
        app: lh-scheduler
        littlehorse.io/active: "true"
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: lh-scheduler
      serviceAccountName: lh-server
      containers:
      - name: lh-scheduler
        # resources:
        #   limits:
        #     cpu: "8"
        #   requests:
        #     cpu: "8"
        image: littlehorse:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: LHORSE_KAFKA_BOOTSTRAP
          value: "lh-kafka-kafka-bootstrap.kafka:9092"
        - name: "LHORSE_KAFKA_GROUP_ID"
          value: "scheduler"
        - name: "LHORSE_KAFKA_GROUP_IID"
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: "LHORSE_KAFKA_STREAMS_STATE_DIR"
          value: "/kafkaStateStores"
        - name: "LHORSE_CLUSTER_PARTITIONS"
          value: "72"
        - name: "LHORSE_TASK_PARTITIONS"
          value: "12"
        - name: "LHORSE_REPLICATION_FACTOR"
          value: "3"
        - name: "LHORSE_NUM_STREAM_THREADS"
          value: "8"
        - name: "LHORSE_NUM_STANDBY_REPLICAS"
          value: "1"
        - name: "LHORSE_COMMIT_INTERVAL"
          value: "50"
        - name: "LHORSE_API_HOST"
          value: "lh-server.default"
        - name: "LHORSE_API_PORT"
          value: "5000"
        ports:
        - containerPort: 5000
        command: ['java', '-cp', '/littleHorse.jar', 'io.littlehorse.App', 'scheduler']
        volumeMounts:
        - name: streams-state
          mountPath: /kafkaStateStores
  volumeClaimTemplates:
  - metadata:
      name: streams-state
      labels:
        littlehorse.io/kafka-state-dir: "true"
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "standard"
      resources:
        requests:
          storage: 1Gi
